export const siteConfig = {
  businessName: 'Pune Fiber Connect',
  eyebrow: 'INDEPENDENT BROADBAND CONNECTION ASSISTANCE',
  phone: '8087341192',
  whatsapp: '918087341192',
  email: 'yogeshtantak543@gmail.com',
  mapsUrl: 'https://maps.app.goo.gl/pxkoiM9s8ZSyg8FWA?g_st=ac',
  hours: 'Mon-Sun · 9:00 AM - 8:00 PM',
  address: 'Pune, Maharashtra, India',
  serviceAreas: ['Kharadi', 'Viman Nagar', 'Hadapsar', 'Magarpatta', 'Wagholi', 'Keshav Nagar', 'Other Pune areas'],
  plans: [
    {
      name: 'Basic Wi-Fi',
      speed: '40 Mbps',
      price: '499',
      data: 'Unlimited',
      planType: 'Wi-Fi',
      benefits: ['Unlimited data', 'Everyday browsing & work from home', 'Xstream Play included'],
    },
    {
      name: 'Fast Wi-Fi',
      speed: '100 Mbps',
      price: '799',
      data: 'Unlimited',
      planType: 'Wi-Fi',
      benefits: ['Unlimited data', 'High-speed 100 Mbps', 'Xstream Play included'],
    },
    {
      name: 'Premium Entertainment',
      speed: '100 Mbps',
      price: '899',
      data: 'Unlimited',
      planType: 'Wi-Fi + TV + OTT',
      benefits: ['Unlimited data', 'HD/SD 350+ channels', 'JioHotstar + Xstream Play'],
      featured: true,
    },
    {
      name: 'Entertainment',
      speed: '100 Mbps',
      price: '999',
      data: 'Unlimited',
      planType: 'Wi-Fi + TV + OTT',
      benefits: ['Unlimited data', 'HD/SD 350+ channels', 'JioHotstar + Xstream Play'],
    },
    {
      name: 'Ultimate TV',
      speed: '100 Mbps',
      price: '1199',
      data: 'Unlimited',
      planType: 'Wi-Fi + TV + OTT',
      benefits: ['Unlimited data', 'HD/SD 350+ channels', 'Netflix + Prime Video + JioHotstar + Apple TV+'],
    },
    {
      name: 'Max Speed',
      speed: '300 Mbps',
      price: '1599',
      data: 'Unlimited',
      planType: 'Wi-Fi + TV + OTT',
      benefits: ['Unlimited data', 'HD/SD 350+ channels', 'Netflix + Prime Video + JioHotstar + Apple TV+'],
    },
    {
      name: 'VIP',
      speed: '1 Gbps',
      price: '3999',
      data: 'Unlimited',
      planType: 'Wi-Fi + OTT',
      benefits: [
        'Blazing fast 1 Gbps speed',
        'Netflix + Prime Video included',
        'Xstream Play included',
        'Unlimited Local & STD calls',
        'Complimentary Wi-Fi Router',
      ],
    },
  ],
}

export const whatsappMessage = 'Hello, I am interested in a broadband connection. Please share available plans for my area.'
